services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/public:/app/public
    - ./frontend/vite.config.js:/app/vite.config.js
    - ./frontend/postcss.config.js:/app/postcss.config.js
    - ./frontend/tailwind.config.js:/app/tailwind.config.js
    ports:
      - "5173:5173"
    depends_on:
      - app

volumes:
  pgdata: